package functions

import _struct "github.com/Andreika228/awesomeProjest1/pkg/struct"

func Team() []_struct.Person {
	var team []_struct.Person
	var person _struct.Person

	person.Num = "23"
	person.FirstName = "Emiliano"
	person.SecondName = "Martínez"
	person.Position = "GK"
	person.Club = "Aston Villa"
	person.Height = "1.95m"
	person.KickLeg = "right"
	person.Matches = "34"
	person.Goals = "0"
	person.Value = " 28mln"
	team = append(team, person)

	person.Num = "12"
	person.FirstName = "Walter"
	person.SecondName = "Benitez"
	person.Position = "GK"
	person.Club = "PSV"
	person.Height = "1.91m"
	person.KickLeg = "right"
	person.Matches = "0"
	person.Goals = "0"
	person.Value = " 12mln"
	team = append(team, person)

	person.Num = "12"
	person.FirstName = "Juan"
	person.SecondName = "Musso"
	person.Position = "GK"
	person.Club = "Atalanta"
	person.Height = "1.91m"
	person.KickLeg = "right"
	person.Matches = "2"
	person.Goals = "0"
	person.Value = " 8mln"
	team = append(team, person)

	person.Num = "1"
	person.FirstName = "Franco"
	person.SecondName = "Armani"
	person.Position = "GK"
	person.Club = "River Plat"
	person.Height = "1.89m"
	person.KickLeg = "right"
	person.Matches = "19"
	person.Goals = "0"
	person.Value = " 1.2mln"
	team = append(team, person)

	person.Num = "13"
	person.FirstName = "Cristian"
	person.SecondName = "Romero"
	person.Position = "CB"
	person.Club = "Tottenhem"
	person.Height = "1.85m"
	person.KickLeg = "right"
	person.Matches = "28"
	person.Goals = "2"
	person.Value = " 65mln"
	team = append(team, person)

	person.Num = "-"
	person.FirstName = "Lucas Martinez"
	person.SecondName = "Quarta"
	person.Position = "CB"
	person.Club = "Fiorentina"
	person.Height = "1.83m"
	person.KickLeg = "right"
	person.Matches = "12"
	person.Goals = "0"
	person.Value = " 14mln"
	team = append(team, person)

	person.Num = "6"
	person.FirstName = "German"
	person.SecondName = "Pezzella"
	person.Position = "CB"
	person.Club = "Betis"
	person.Height = "1.87m"
	person.KickLeg = "right"
	person.Matches = "39"
	person.Goals = "3"
	person.Value = " 5mln"
	team = append(team, person)

	person.Num = "19"
	person.FirstName = "Nicolas"
	person.SecondName = "Otamendi"
	person.Position = "CB"
	person.Club = "Benfica"
	person.Height = "1.83m"
	person.KickLeg = "right"
	person.Matches = "109"
	person.Goals = "6"
	person.Value = " 1.5mln"
	team = append(team, person)

	person.Num = "3"
	person.FirstName = "Nicolas"
	person.SecondName = "Tagliafico"
	person.Position = "CB"
	person.Club = "Lion"
	person.Height = "1.72m"
	person.KickLeg = "left"
	person.Matches = "55"
	person.Goals = "1"
	person.Value = " 8mln"
	team = append(team, person)

	person.Num = "8"
	person.FirstName = "Marcos"
	person.SecondName = "Acuna"
	person.Position = "LB"
	person.Club = "Sevilia"
	person.Height = "1.72m"
	person.KickLeg = "left"
	person.Matches = "56"
	person.Goals = "0"
	person.Value = " 6mln"
	team = append(team, person)

	person.Num = "2"
	person.FirstName = "Nahuel"
	person.SecondName = "Molina"
	person.Position = "RB"
	person.Club = "Athletico Madrid"
	person.Height = "1.75m"
	person.KickLeg = "right"
	person.Matches = "35"
	person.Goals = "1"
	person.Value = " 45mln"
	team = append(team, person)

	person.Num = "4"
	person.FirstName = "Gonzalo"
	person.SecondName = "Montiel"
	person.Position = "RB"
	person.Club = "Notighem Forest"
	person.Height = "1.75m"
	person.KickLeg = "right"
	person.Matches = "24"
	person.Goals = "1"
	person.Value = " 10mln"
	team = append(team, person)

	person.Num = "-"
	person.FirstName = "Pablo"
	person.SecondName = "Maffeo"
	person.Position = "RB"
	person.Club = "Malorka"
	person.Height = "1.72m"
	person.KickLeg = "right"
	person.Matches = "0"
	person.Goals = "0"
	person.Value = " 8mln"
	team = append(team, person)

	person.Num = "18"
	person.FirstName = "Guido"
	person.SecondName = "Rodriguez"
	person.Position = "CDM"
	person.Club = "Betis"
	person.Height = "1.85m"
	person.KickLeg = "right"
	person.Matches = "29"
	person.Goals = "1"
	person.Value = " 24mln"
	team = append(team, person)

	person.Num = "5"
	person.FirstName = "Leandro"
	person.SecondName = "Paredes"
	person.Position = "CDM"
	person.Club = "Roma"
	person.Height = "1.80m"
	person.KickLeg = "right"
	person.Matches = "58"
	person.Goals = "5"
	person.Value = " 8mln"
	team = append(team, person)

	person.Num = "17"
	person.FirstName = "Enzo"
	person.SecondName = "Fernandez"
	person.Position = "CM"
	person.Club = "Chelsea"
	person.Height = "1.78m"
	person.KickLeg = "right"
	person.Matches = "19"
	person.Goals = "3"
	person.Value = " 80mln"
	team = append(team, person)

	person.Num = "20"
	person.FirstName = "Alexis"
	person.SecondName = "Mac Allister"
	person.Position = "CM"
	person.Club = "Liverpool"
	person.Height = "1.76m"
	person.KickLeg = "right"
	person.Matches = "23"
	person.Goals = "1"
	person.Value = " 65mln"
	team = append(team, person)

	person.Num = "14"
	person.FirstName = "Exequiel"
	person.SecondName = "Palacios"
	person.Position = "CM"
	person.Club = "Bayer"
	person.Height = "1.77m"
	person.KickLeg = "right"
	person.Matches = "28"
	person.Goals = "0"
	person.Value = " 40mln"
	team = append(team, person)

	person.Num = "7"
	person.FirstName = "Rodrigo"
	person.SecondName = " de Paul"
	person.Position = "CM"
	person.Club = "Atletico Madrid"
	person.Height = "1.80m"
	person.KickLeg = "right"
	person.Matches = "60"
	person.Goals = "2"
	person.Value = " 30mln"
	team = append(team, person)

	person.Num = "16"
	person.FirstName = "Giovani"
	person.SecondName = "Lo Celso"
	person.Position = "CAM"
	person.Club = "Tottenhem"
	person.Height = "1.77m"
	person.KickLeg = "left"
	person.Matches = "48"
	person.Goals = "2"
	person.Value = " 16mln"
	team = append(team, person)

	person.Num = "21"
	person.FirstName = "Lucas"
	person.SecondName = "Ocampos"
	person.Position = "LW"
	person.Club = "Sevilia"
	person.Height = "1.87m"
	person.KickLeg = "both legs"
	person.Matches = "12"
	person.Goals = "2"
	person.Value = " 12mln"
	team = append(team, person)

	person.Num = "15"
	person.FirstName = "Nicolas"
	person.SecondName = "Gonzalez"
	person.Position = "RW"
	person.Club = "Fiorentina"
	person.Height = "1.80m"
	person.KickLeg = "left"
	person.Matches = "30"
	person.Goals = "5"
	person.Value = " 40mln"
	team = append(team, person)

	person.Num = "10"
	person.FirstName = "Leo"
	person.SecondName = "Messi"
	person.Position = "RW(captain)"
	person.Club = "Inter Miami"
	person.Height = "1.70m"
	person.KickLeg = "left"
	person.Matches = "180"
	person.Goals = "106"
	person.Value = " 35mln"
	team = append(team, person)

	person.Num = "11"
	person.FirstName = "Angel"
	person.SecondName = "Di Maria"
	person.Position = "RW"
	person.Club = "Benfica"
	person.Height = "1.78m"
	person.KickLeg = "left"
	person.Matches = "136"
	person.Goals = "29"
	person.Value = " 5mln"
	team = append(team, person)

	person.Num = "9"
	person.FirstName = "Julian"
	person.SecondName = "Alvarez"
	person.Position = "CF"
	person.Club = "Manchester City"
	person.Height = "1.70m"
	person.KickLeg = "right"
	person.Matches = "28"
	person.Goals = "7"
	person.Value = " 90mln"
	team = append(team, person)

	person.Num = "21"
	person.FirstName = "Paulo"
	person.SecondName = "Dybala"
	person.Position = "CF"
	person.Club = "Roma"
	person.Height = "1.77m"
	person.KickLeg = "left"
	person.Matches = "38"
	person.Goals = "3"
	person.Value = " 25mln"
	team = append(team, person)

	person.Num = "22"
	person.FirstName = "Lautaro"
	person.SecondName = "Martinez"
	person.Position = "ST"
	person.Club = "Inter"
	person.Height = "1.74m"
	person.KickLeg = "right"
	person.Matches = "54"
	person.Goals = "21"
	person.Value = " 110mln"
	team = append(team, person)
	return team

}
